/* 제미나이 프롬프트 대장 — 「탐정 망고의 춤추는 대수사선」 사건 1
   규칙: PRD 0.7 ART-1~ART-10 / 바이블 9장. 파일명은 data/case-01.json 의 선언과 같아야 한다. */

export var STYLE = {
  cel: "hand-drawn 2D animation cel style, thick dark-brown outlines #4a3428 about 2.6px, flat matte colors with exactly one hard-edged shadow tone, big round eyes with a single tiny dot highlight, exaggerated proportions with head about 45% of body height, autumn muted palette (mustard #d6a83c, teal #3f7c86, brick #b34a3a, cream #fbf7ee, olive #7d8f5c), storybook children's book quality, plain flat cream #fbf7ee background, no gradient, no text, no watermark, no border",
  paint: "gouache painting on textured paper, visible brush strokes, no outlines, low saturation, warm late-afternoon light from the left, soft vignette at the corners, three clear depth layers (foreground / middle / far), autumn European-style small town of animals, storybook illustration, no characters, no people, no animals, no text, no watermark",
  icon: "single small object icon, hand-drawn cel style, thick dark-brown outline #4a3428, flat matte fill, one hard shadow tone, centered, isolated on plain flat cream #fbf7ee background, no shadow on the ground, no text, no label, no border, simple and readable at 28 pixels",
  ban: "금지: 실사풍, 3D 렌더, 그라데이션 배경, 글자·말풍선·서명, 사람(인간), 무기, 로고, 기존 애니메이션 작품 언급. 「지브리풍」·「디즈니풍」처럼 특정 작품 이름을 쓰지 않는다(ART-10). 망고의 머리 위 회색은 실제 고양이의 털 무늬다 — 모자로 그려지면 다시 뽑거나 꼭지를 지워야 한다(ART-2)."
};

export var MANGO_ID = "white cat, a dark grey FUR MARKING on top of the head — it is fur, not clothing: flat against the head with soft irregular fur edges, NO hat, NO cap, no brim, no seam, and nothing sticking up on top — shifted to the RIGHT so the LEFT ear stays white, a brown tabby patch beside the RIGHT ear reaching down to the cheek, one white stripe from forehead down to the nose, yellow-green eyes #b9c96a, pink nose and inner ears, chubby pear-shaped body with short legs, teal vest #3f7c86, brick-red bow tie #b34a3a, brown leather satchel, brass magnifying glass, NO hat";

export var GROUPS = [

/* ───────────────────────── 1. 망고 ───────────────────────── */
{
  title: "1. 망고 — 주인공 (가장 먼저 확정할 것)",
  note: "망고는 이후 모든 그림의 기준이 된다. 4장이 다 나온 뒤 나란히 놓고 정체성 6요소가 흔들리지 않는지 확인하고, 흔들리면 그 장만 다시 뽑는다. 제미나이 대화 하나에서 4장을 연달아 뽑는 편이 인물 일관성이 좋다 — 첫 장이 마음에 들면 「같은 캐릭터로, 표정만 …으로 바꿔서」라고 이어서 요청한다.",
  items: [
    { file:"mango-def.png", label:"기본",
      p:"A friendly detective cat character, front-facing bust portrait from the chest up. "+MANGO_ID+", calm confident expression with a slight smile, eyes looking straight at the viewer. "+STYLE.cel },
    { file:"mango-sp.png", label:"놀람",
      p:"The SAME detective cat character, front-facing bust portrait, identical design and colors. "+MANGO_ID+", surprised expression: eyes wide open and round, mouth a small open circle, both ears perked straight up, one small exclamation-shaped tuft of fur standing up. "+STYLE.cel },
    { file:"mango-fl.png", label:"당황 (네 번째 칸 = 본성)",
      p:"The SAME detective cat character, front-facing bust portrait, identical design and colors. "+MANGO_ID+", flustered expression: eyes glancing away to the side, one eyebrow raised, a tiny nervous smile, two small sweat drops near the temple, ears tilted slightly back. "+STYLE.cel },
    { file:"mango-joy.png", label:"기쁨 (해결 화면)",
      p:"The SAME detective cat character, front-facing bust portrait, identical design and colors. "+MANGO_ID+", delighted expression: eyes closed into happy upward arcs, wide open smile, cheeks slightly rounded, holding the magnifying glass up beside the face. "+STYLE.cel },
    { file:"mango-full.png", label:"전신 (표지·홈 화면용)", size:"1024×1536",
      p:"Full body standing pose of the same detective cat character, three-quarter view, feet visible. "+MANGO_ID+", standing upright on two short legs, one paw holding the magnifying glass at chest height, leather satchel hanging at the hip, confident relaxed posture, tail curving up behind. "+STYLE.cel }
  ]
},

/* ───────────────────────── 2. 사건 1 인물 ───────────────────────── */
{
  title: "2. 사건 1 인물 6명",
  note: "★★ 망고를 두 번 뽑아 보고 정한 순서 — 반드시 두 단계로 갑니다. ① 먼저 기본 표정 한 장만 뽑아 마음에 들 때까지 고칩니다(아래 인물별 프롬프트 사용). ② 그 그림을 제미나이에 첨부하고 「이 캐릭터 그대로, 표정만 바꿔 2x2로」 주문합니다. 왜 두 단계인가: 표정을 낱장으로 따로 주문하면 머리 크기·팔 자세·소품 위치가 칸마다 달라져 게임에서 표정이 바뀔 때 얼굴이 툭 튑니다. 반대로 「모든 칸이 똑같아야 한다」를 글로만 앞세우면 모델이 똑같이 그리기 쉬운 쪽으로 캐릭터를 깎아 버립니다 — 망고의 회색 무늬·코 흰 줄·수염이 사라지고 확대경이 가슴 목걸이가 됐습니다. 기준 그림을 첨부하면 둘 다 막힙니다. 용의자는 반박 성공 시 표정이 바뀌는 게 연출의 핵심이므로 이 순서를 꼭 지킵니다. 받은 시트 한 장은 art/slice-sheet.py 가 칸을 찾아 머리 크기와 윤곽으로 정렬해 파일로 만듭니다. ★ 칸 사이를 반드시 띄워 달라고 하세요 — 인물이 붙어 있으면 자르는 선이 팔·꼬리를 지나가 조각이 테두리에 남고, 초상을 머리·목까지만 잡아야 합니다(콩이에서 실제로 발생). 실루엣 규칙(바이블 9.5): 네 칸을 검은 실루엣으로 바꿔 다른 인물과 구별되는지 확인합니다.",
  items: [
    { file:"(2단계) <이름>-sheet.png", label:"★ 2단계 — 마음에 든 그림을 첨부하고 이 글을 넣으세요", size:"2x2 한 장",
      p:"※ 첨부하는 그림은 반드시 <b>그 인물 자신의 1단계 그림</b>이어야 합니다. 다른 인물(예: 망고)의 그림을 첨부하면 그 인물의 옷과 소품이 따라옵니다 — 콩이에 망고 그림을 첨부했다가 급식 도우미가 탐정 조끼와 확대경을 들고 나왔습니다.\n\nUse the attached image as the exact character reference. Keep this character's design EXACTLY as drawn — same fur markings and their exact placement, same eyes, same clothing and props EXACTLY as in the attached image and nothing else added, same thick dark-brown outline weight, same flat matte colors.\n\nDraw this same character FOUR times in a 2x2 grid, front-facing bust portraits, evenly spaced on one continuous plain flat cream #fbf7ee background with no dividing lines, no borders, no text. Leave a clear empty gap between the panels — the figures must NOT touch or overlap each other.\n\nThe head must be the SAME SIZE and at the SAME HEIGHT in all four (identical eye line), the body and arms in the SAME pose, every prop in the SAME position. ONLY the face changes:\n\nTop-left: the character's calm default expression.\nTop-right: surprised — eyes wide and round, mouth a small open circle, ears perked up.\nBottom-left: [네 번째 칸 — 인물의 본성을 여기에. 콩순이=눈굴림 / 도토=분노 / 모리=당황(눈은 내리깐 채) / 양 아주머니=난처함 / 밤이=신남]\nBottom-right: [필요하면 네 번째 표정을 더. 없으면 이 줄을 지우고 2x2 대신 1x3 으로 주문]\n\nDo not redesign, simplify, or prettify the character. Do not change the fur markings. Match the reference drawing." },
    { file:"(1단계)", label:"★ 1단계 — 먼저 기본 표정 한 장만",
      p:"아래 인물별 프롬프트 중 「기본」 한 장만 먼저 뽑으세요. 무늬 위치·소품·선 굵기가 마음에 들 때까지 이 한 장만 고칩니다. 이 그림이 그 인물의 기준이 되므로, 여기서 타협하면 표정 네 칸이 전부 그 상태로 굳습니다. 마음에 들면 그 파일을 첨부해 위의 2단계 프롬프트를 넣으세요 — 첨부는 반드시 그 인물 자신의 그림입니다. 1단계에서는 아무 그림도 첨부하지 않습니다(다른 인물 그림이 섞이면 옷과 소품이 옮겨 붙습니다). 받은 시트 한 장을 올려 주시면 칸을 잘라 눈 위치를 맞춰 파일로 만들어 드립니다." },
    { file:"kongi-def.png", label:"콩이 · 기본 — 너구리, 앞치마 없음",
      p:"An anthropomorphic raccoon girl as an elementary school lunch helper, front-facing bust portrait from the chest up, single figure, centered. Wide round pot-shaped body, short arms, a bushy ringed tail curving up behind one shoulder, grey-brown fur with the classic dark raccoon eye mask, round black eyes, small dark nose, small rounded ears. CLOTHING — she is a lunch helper, NOT a detective: a simple short-sleeved cream shirt and nothing else. NO vest, NO bow tie, NO bag or strap, NO magnifying glass, NO apron, NO hat, no accessories of any kind. Her hands are empty and rest at her sides. Expression: neutral and slightly stiff, as if being questioned about something she did. "+STYLE.cel },
    { file:"kongi-sp.png", label:"콩이 · 놀람",
      p:"The SAME raccoon lunch helper character, identical design and colors, front-facing bust portrait, no apron. Startled expression: both eyes wide and round, mouth open in a small gasp, tail fur puffed up. "+STYLE.cel },
    { file:"kongi-fl.png", label:"콩이 · 거짓말 눈굴림 (반박당한 순간)",
      p:"The SAME raccoon lunch helper character, identical design and colors, front-facing bust portrait, no apron. Caught-in-a-lie expression: pupils rolled up and to the upper corner avoiding the viewer, a forced stiff smile, three sweat drops on the forehead, shoulders slightly hunched. "+STYLE.cel },

    { file:"kongsun-STEP1.png", label:"콩순이 · 1단계 — 기본 한 장 (★ 콩이 기본 그림을 첨부할 것)",
      note:"쌍둥이라 얼굴·몸이 콩이와 같아야 하므로, 이 인물만은 1단계에서 콩이의 기본 그림을 첨부한다. 얼룩은 반드시 갈색 — 도토리묵이다. 빨간 얼룩(김치)으로 나오면 추리가 무너지므로 다시 뽑는다.",
      p:"Using the attached raccoon as the exact reference, draw her TWIN SISTER: keep the face, head shape, eye mask, fur colors, body shape and tail identical to the attached image. One single front-facing bust portrait, calm innocent expression. Two changes only: (1) she wears a PALE PINK apron with shoulder straps over the same cream shirt, and the apron has TWO soft BROWN blotches on the chest — a larger one and a smaller one beside it, the muddy brown color of acorn jelly, clearly BROWN and absolutely NOT red, NOT orange, NOT pink; (2) a small brick-red ribbon #b34a3a sits on top of her head between the ears. She is NOT a detective — no vest, no bow tie, no bag, no magnifying glass, no hat. Paws resting at her sides so the apron stains stay fully visible. "+STYLE.cel },

    { file:"kongsun-SHEET.png", label:"콩순이 · 2단계 — 표정 3칸 (★ 승인된 콩순이 1단계 그림을 첨부할 것)",
      note:"첨부는 반드시 콩순이 자신의 1단계 그림. 다른 인물 그림을 붙이면 복장이 옮겨 붙는다. 받은 파일은 art/slice-sheet.py <파일> kongsun def,sp,fl 로 자른다.",
      p:"Using the attached character as the exact reference, draw the SAME raccoon girl three times in one image, side by side in a single row, in this order: (1) calm innocent, looking straight ahead; (2) shocked — eyes wide, both paws raised to the cheeks, mouth a small round O, ears flattened sideways; (3) evasive — eyes looking down and to the side, lips pressed into a thin line, two sweat drops on the temple. Keep her face, body, pale pink apron, the TWO BROWN blotches on the apron, and the brick-red head ribbon exactly as in the attached image in all three panels — same size, same colors, same line weight. Leave a clear empty gap between the panels — the figures must NOT touch or overlap each other. Plain flat cream #fbf7ee background, no panel borders, no frames, no text, no labels. "+STYLE.cel },

    { file:"doto-STEP1.png", label:"도토 · 1단계 — 기본 한 장 (★ 콩이 기본 그림을 「스타일 참고용」으로 첨부)",
      note:"★ 새 동물 종은 첨부 없이 뽑으면 스타일이 무너진다 — 도토를 글로만 주문했더니 외곽선이 거의 없고(진한 선 3.6% · 기준 18~20%) 채도가 두 배(0.52 · 기준 0.26~0.32)인 다른 화풍이 나왔고, 인물이 화면을 98% 채워 꼬리가 잘렸다. 그래서 승인된 인물 그림을 붙이되 「베낄 것은 화풍뿐」을 명시한다. 종·얼굴·복장을 베끼지 말라고 못박지 않으면 콩이가 망고 옷을 입고 나왔던 일이 되풀이된다. ★ 꼬리는 또렷한 갈색에 고리 무늬가 없어야 한다 — 도토를 지우는 근거가 「나간 건 회색 꼬리였는데 도토는 갈색이다」 하나뿐이다.",
      p:"The attached picture is a STYLE REFERENCE ONLY. Copy from it: the thick uniform dark-brown outline weight, the flat matte fill with exactly one hard-edged shadow tone, the eye style, the head-to-body proportion, the low-saturation muted palette, the framing and the plain background. Do NOT copy the animal species, the face, the clothing or any props from it. Draw a completely different animal: an anthropomorphic SQUIRREL as a grumpy tree-house landlord — not a raccoon. One single front-facing bust portrait. Tall narrow vertical body, very large fluffy tail curving up behind the head; the tail is the biggest shape in the picture. The tail and body fur are a MUTED, DESATURATED reddish-brown, clearly BROWN and absolutely NOT grey and NOT bright orange; the tail is ONE SOLID BROWN with NO rings, NO stripes and NO bands of any kind. Cream chest FUR — he wears no shirt and no clothing at all. Tufted ear tips, holding ONE acorn in both front paws at chest height. Large eyes with heavy drooping upper lids and a single tiny dot highlight in each, plus a slight frown — grumpy and just woken from a nap. He is NOT a detective: no vest, no bow tie, no bag, no magnifying glass, no hat. Thick dark-brown outlines #4a3428 about 2.6px on every edge including the tail. NO gradients, NO airbrushed or soft shading, NO glossy highlights. Show the WHOLE figure including the entire tail, with a generous empty margin on all four sides — nothing may touch or be cut off by the edge of the picture. "+STYLE.cel },

    { file:"doto-SHEET.png", label:"도토 · 2단계 — 표정 3칸 (★ 승인된 도토 1단계 그림을 첨부할 것)",
      note:"★ 꼬리 큰 인물은 「칸마다 꼬리 필수」와 「칸 사이 띄우기」가 서로 부딪힌다. 1차: 꼬리를 칸마다 요구하지 않아 놀람 칸에만 꼬리가 생겼다(기본 초상에 꼬리가 없으면 「도토는 갈색이야」 소거 근거를 볼 수 없다). 2차: 꼬리를 요구하니 세 칸 모두 꼬리가 생겼지만 꼬리가 옆으로 뻗어 인물이 붙었고, 꼬리가 옆 머리까지 닿아 머리 분리 침식이 통하지 않아 자르기가 실패했다. 해법은 꼬리를 옆이 아니라 몸 뒤로 세우고 인물을 작게 그리게 하는 것이다 — 3차에서 통과(머리 중심 흔들림 1.5px). 이래도 붙어 나오면 표정을 한 장씩 따로(매번 1단계 그림을 첨부) 받아 slice-sheet.py 로 정렬한다 — 첨부가 있으면 낱장도 정렬된다. 첨부는 반드시 도토 자신의 1단계 그림. 분노 칸(doto-ang)은 게임이 쓰는 곳이 없어 만들지 않는다. 받은 파일은 art/slice-sheet.py <파일> doto def,sp,fl 로 자른다.",
      p:"Using the attached character as the exact reference, draw the SAME squirrel three times in one image, side by side in a single row, in this order: (1) sleepy and grumpy, half-lidded eyes, slight frown, looking straight ahead; (2) startled awake — eyes suddenly wide open and round, mouth open in a small gasp; (3) taken aback — eyes blinking wide, mouth a small wavy line, one paw scratching the back of the head. Every panel must show his large bushy tail — one solid muted reddish-brown with NO rings, NO stripes and NO bands. IMPORTANT: in every panel the tail rises straight up BEHIND his head and body, like a plume directly behind him, and does NOT sweep out to the left or right. Keep his face, body, the cream chest and the single acorn exactly as in the attached image in all three panels — same size, same colors, same line weight. Draw the three figures SMALL, each one filling only the middle of its own third of the picture, so that there is a wide band of empty cream background between them: no part of one figure, tail included, may touch, overlap or reach into a neighbouring figure, and the gap between two figures must be at least as wide as one of their heads. Plain flat cream #fbf7ee background, no panel borders, no frames, no text, no labels. "+STYLE.cel },

    { file:"mori-STEP1.png", label:"모리 · 1단계 — 기본 한 장 (★ 콩이 기본 그림을 「화풍 참고용」으로 첨부)",
      note:"★ 눈은 모든 칸에서 반드시 내리깔아야 한다. 정면을 보는 모리(mori_direct)는 사건 18 전용 연출이라 미리 만들면 시즌1 최대 장치가 죽는다 — 절대 만들지 않는다. ★ 소매의 흙은 붉은 흙이어야 한다. 창턱 발자국이 붉은 흙이고 그게 두더지 것이라는 게 시즌 서사의 씨앗이므로, 색이 다르면 씨앗이 끊긴다. 실루엣은 일부러 밋밋해야 한다(바이블 9.5) — 튀는 부분이 없는 것이 모리의 특징이다.",
      p:"The attached picture is a STYLE REFERENCE ONLY. Copy from it: the thick uniform dark-brown outline weight, the flat matte fill with exactly one hard-edged shadow tone, the eye style, the head-to-body proportion, the low-saturation muted palette, the framing and the plain background. Do NOT copy the animal species, the face, the clothing or any props from it. Draw a completely different animal: an anthropomorphic MOLE as a shy village librarian, not a raccoon. One single front-facing bust portrait. Small simple round body with NO protruding silhouette feature — no big tail, no wings, nothing sticking out. Dark grey velvet fur, small pink nose, round spectacles, hugging a stack of books against the chest, wearing a mustard cardigan. CRITICAL: the eyes are cast DOWNWARD behind the glasses and never meet the viewer, with a gentle timid expression. Two small planted details: dried REDDISH-BROWN earth smudged on one sleeve cuff, and a faint reflection of a large tree in one lens. "+STYLE.cel },

    { file:"mori-SHEET.png", label:"모리 · 2단계 — 표정 3칸 (★ 승인된 모리 1단계 그림을 첨부할 것)",
      note:"세 칸 모두에서 눈을 내리깐 채여야 한다. 놀라도, 당황해도 시선은 올라오지 않는다 — 이것이 모리를 모리로 만드는 유일한 규칙이다. 받은 파일은 art/slice-sheet.py <파일> mori def,sp,fl 로 자른다.",
      p:"Using the attached character as the exact reference, draw the SAME mole three times in one image, side by side in a single row, in this order: (1) calm and timid, hugging the books; (2) startled — shoulders jumping up, mouth a small open circle, ears tucked back, still hugging the books; (3) flustered — two clear sweat drops on the forehead, both cheeks blushing pink, mouth a small wavy line, hugging the books tighter. CRITICAL: in every one of the three panels the eyes stay cast DOWNWARD behind the glasses and never look at the viewer, not even in the startled panel. Keep his face, body, round spectacles, mustard cardigan, the stack of books and the reddish earth smudge on the cuff exactly as in the attached image in all three panels — same size, same colors, same line weight. Draw the three figures SMALL, each one filling only the middle of its own third of the picture, so that there is a wide band of empty cream background between them: no part of one figure may touch, overlap or reach into a neighbouring figure, and the gap between two figures must be at least as wide as one of their heads. Plain flat cream #fbf7ee background, no panel borders, no frames, no text, no labels. "+STYLE.cel },

    { file:"sheep-STEP1.png", label:"양 아주머니 · 1단계 — 기본 한 장 (★ 콩이 기본 그림을 「화풍 참고용」으로 첨부)",
      note:"★ 앞치마는 올리브색이어야 한다. 크림색으로 그리면 「걸이에서 사라진 건 크림색이니 콩이 것」이라는 추론이 흐려진다 — 콩이가 반박당할 때 「크림색이 저만 있는 건 아니잖아요」라고 항변하므로, 크림색 앞치마를 입은 어른이 화면에 있으면 그 항변에 힘이 실린다. 연분홍도 안 된다(콩순이). ★ 열쇠는 보이게 그린다 — 「앞문 열쇠는 나만 있어요」가 증언이자 소거의 배경이다.",
      p:"The attached picture is a STYLE REFERENCE ONLY. Copy from it: the thick uniform dark-brown outline weight, the flat matte fill with exactly one hard-edged shadow tone, the eye style, the head-to-body proportion, the low-saturation muted palette, the framing and the plain background. Do NOT copy the animal species, the face, the clothing or any props from it. Draw a completely different animal: an anthropomorphic SHEEP as a kind middle-aged school cafeteria manager, not a raccoon. One single front-facing bust portrait. Low wide rounded silhouette made of soft cloud-like curly cream wool, gentle dark eyes with horizontal pupils, small tan muzzle, short curved horns, a headscarf pushed back. She wears an OLIVE GREEN apron — clearly olive green, absolutely NOT cream, NOT white and NOT pink — over a plain dress. A single brass key hangs on a cord at her waist, clearly visible. Warm, worried but composed expression. "+STYLE.cel },

    { file:"sheep-SHEET.png", label:"양 아주머니 · 2단계 — 표정 3칸 (★ 승인된 양 아주머니 1단계 그림을 첨부할 것)",
      note:"양털이 옆으로 퍼져 도토처럼 칸이 붙기 쉽다. 붙어 나오면 자르기가 실패하므로 인물을 작게 그리라고 못박았다. 받은 파일은 art/slice-sheet.py <파일> sheep def,sp,fl 로 자른다.",
      p:"Using the attached character as the exact reference, draw the SAME sheep three times in one image, side by side in a single row, in this order: (1) warm and composed, worried but calm; (2) startled — eyes wide, both hooves raised to the cheeks, mouth a small round O; (3) troubled — brows drawn together, mouth pressed into a thin line, one hoof to the chest. Keep her face, body, the OLIVE GREEN apron, the headscarf, the horns and the brass key at her waist exactly as in the attached image in all three panels — same size, same colors, same line weight. Draw the three figures SMALL, each one filling only the middle of its own third of the picture, so that there is a wide band of empty cream background between them: no part of one figure may touch, overlap or reach into a neighbouring figure, and the gap between two figures must be at least as wide as one of their heads. Plain flat cream #fbf7ee background, no panel borders, no frames, no text, no labels. "+STYLE.cel },

    { file:"bami-STEP1.png", label:"밤이 · 1단계 — 기본 한 장 (★ 콩이 기본 그림을 「화풍 참고용」으로 첨부)",
      note:"1차에서 두 가지가 어긋났다 — 가시가 화면 좌우로 잘렸고(밤이를 밤이답게 만드는 실루엣이다), 돋보기를 눈에 대고 있어 머리만 했다. 돋보기가 크면 망고와 헷갈린다. 둘 다 프롬프트에 못박아 2차에서 통과. 가시가 옆으로 뻗어 2단계에서 칸이 붙기 쉽다.",
      p:"The attached picture is a STYLE REFERENCE ONLY. Copy from it: the thick uniform dark-brown outline weight, the flat matte fill with exactly one hard-edged shadow tone, the EYE STYLE, the FRAMING, the head-to-body proportion, the low-saturation muted palette, and the plain background. Do NOT copy the animal species, the face, the clothing or any props from it. Draw a completely different animal: an anthropomorphic young HEDGEHOG as an eager apprentice detective, not a raccoon. One single front-facing BUST portrait, cropped at the chest. Draw him a little smaller in the frame so that his ENTIRE spiky outline is inside the picture with clear empty background all around it — the whole round spiky silhouette must be visible and must never touch or run off any edge of the image. Round body covered in short spiky quills forming a spiky circular silhouette, warm brown quills with a cream face, huge sparkling round eyes each with a single tiny white dot highlight, tiny black nose, wearing a small teal scarf. He holds a SMALL brass magnifying glass down beside his chin, lowered away from his face so it covers nothing — the lens must be much smaller than his head, about the size of one eye, clearly a child's magnifier. Do NOT hold it over the eye and do NOT magnify the eye through it. Bright excited expression with an open smile. "+STYLE.cel },

    { file:"bami-SHEET.png", label:"밤이 · 2단계 — 표정 3칸 (★ 승인된 밤이 1단계 그림을 첨부할 것)",
      note:"가시가 옆으로 뻗으므로 인물을 작게 그리라고 못박았다. 받은 파일은 art/slice-sheet.py <파일> bami def,sp,fl 로 자른다.",
      p:"Using the attached character as the exact reference, draw the SAME hedgehog three times in one image, side by side in a single row, in this order: (1) bright and eager, open smile; (2) startled — eyes huge and round, quills bristling outward slightly, mouth a small O; (3) delighted — eyes squeezed into happy arcs, both paws raised, a wide grin. Keep his face, body, the brown quills, the cream face, the teal scarf and the small magnifying glass exactly as in the attached image in all three panels — same size, same colors, same line weight. Draw the three figures SMALL, each one filling only the middle of its own third of the picture, so that there is a wide band of empty cream background between them: no part of one figure may touch, overlap or reach into a neighbouring figure, and the gap between two figures must be at least as wide as one of their heads. Plain flat cream #fbf7ee background, no panel borders, no frames, no text, no labels. "+STYLE.cel }
  ]
},

/* ───────────────────────── 3. 배경 ───────────────────────── */
{
  title: "3. 사건 1 배경 — 급식실 (가로 2:1)",
  note: "확대경으로 훑는 화면이라 가장 공들일 그림이다. 제미나이가 물건을 정확한 자리에 놓아 주지는 않으므로, 순서를 반대로 한다 — 먼저 마음에 드는 배경을 얻고, 그 다음 art/spots.html 로 조사 지점 좌표를 그림에 맞춰 다시 찍는다. 배경 프롬프트는 「무엇이 화면 어디쯤에 있어야 하는가」까지 적어 두되, 어긋나면 좌표를 고치는 쪽이 빠르다.",
  items: [
    { file:"scene-01-cafeteria.webp", label:"급식실 (본 배경) — 단서 10곳이 그림 안에 있어야 한다",
      note:"★ 이 그림은 단서 목록이다. 바닥 부스러기는 반드시 갈색이어야 한다 — 「pale crumbs」라고 썼더니 흰 부스러기가 나왔는데, 앞치마 얼룩 단서가 「김치는 빨간데 이건 갈색, 도토리묵 색」으로 추리를 맺으므로 같은 묵이 두 색으로 보이면 안 된다. 조사 지점 10곳이 실제로 그려져 있지 않으면 확대해도 볼 것이 없다. 특히 세 가지는 추리의 근거라 틀리면 게임이 거짓말을 한다 — ① 앞치마 걸이는 정확히 두 개이고 둘 다 비어 있어야 한다(하나라도 걸려 있으면 「사라진 건 크림색」이 무너진다) ② 통은 양쪽에 손잡이가 하나씩이어야 한다(「둘이 들어야 한다」의 유일한 근거) ③ 창턱 바깥 발자국은 붉은 흙, 뒷마당 흙은 검은 흙 — 두 색이 구별되어야 「밖에서 들여다본 사람은 뒷마당 사람이 아니다」가 성립한다. 뒷문은 안쪽에만 밀대가 있고 바깥에는 손잡이가 없어야 하며, 끈은 손잡이가 아니라 문틀 걸쇠에 걸린다. 받은 뒤 art/make-bg.py 로 2:1·1440x720·WebP 로 맞추고, art/spots.html 로 조사 지점 좌표를 그림에 맞춰 다시 찍는다.",
      p:"Interior of an elementary school cafeteria kitchen in an autumn animal village, completely empty of any characters, horizontal 2:1 composition, viewed straight on from inside the room. LEFT: a tall window with a clearly visible INNER latch fastened shut, a wooden windowsill; on the OUTER ledge of that sill, a few very small footprints in REDDISH-BROWN earth with the toes pointing INWARD toward the room; a plain wooden chair standing below the window. LEFT OF CENTRE: a long stainless steel serving counter running left to right, bare, with one obvious DAMP PATCH on its surface where something round used to stand. UPPER LEFT OF CENTRE: a cork notice board on the wall with one freshly pasted notice, the paste still wet and glossy at the edges. CENTRE: a refrigerator; behind it a stainless sink area where the washing-up is HALF finished — clean dishes stacked and drying on one side, dirty dishes still in the basin on the other; on the wall above, EXACTLY TWO apron hooks, and BOTH hooks are completely EMPTY. FLOOR: a faint trail of crumbs running along the floor from the serving counter toward the back door; the crumbs are the muddy BROWN colour of acorn jelly, the same brown as the stain on the apron, never white and never pale. RIGHT: a heavy back door standing ajar, with a push-bar on the INSIDE face and NO handle at all on the outside; a cream-coloured fabric apron tie is snagged on the metal catch plate of the door frame on the outside, not on any handle. BEYOND THE DOOR, the back yard: soil that is clearly DARK, almost black, in a flower bed; lying on its side in that flower bed an empty round food tub with ONE STURDY HANDLE ON EACH OF ITS TWO SIDES; and further back a large acorn tree. Keep every one of these objects clearly readable and unobstructed, since the player inspects them under a magnifying glass. "+STYLE.paint },

    { file:"scene-01-cafeteria-night.webp", label:"같은 급식실 · 해결 장면용 (선택)", size:"1440×720",
      p:"The SAME elementary school cafeteria kitchen interior, identical layout and furniture, empty of characters, horizontal 2:1 composition, but now lit by warm evening light — deep amber light through the window, longer soft shadows, the back door closed. "+STYLE.paint }
  ]
},

/* ───────────────────────── 4. 표지 ───────────────────────── */
{
  title: "4. 표지",
  note: "첫 화면 배경으로 깔린다. 글자는 게임이 얹으므로 그림에 제목을 넣지 않는다. 가운데 위쪽은 카드가 덮으므로, 중요한 것을 화면 정중앙에 두지 않는 편이 좋다.",
  items: [
    { file:"cover-01.webp", label:"표지 (첫 화면 배경)", size:"1440×720 → WebP 250KB 이하",
      p:"Title-screen illustration for a children's detective mystery game, horizontal 2:1 composition, empty middle area left clear for a title card. An autumn animal village square at dusk seen from a low angle: a great old zelkova tree with golden leaves on the right, warm lantern light, cobblestones, a small detective office window glowing on the left, scattered fallen leaves in the foreground, a long thin shadow of a small cat with a magnifying glass stretching across the cobblestones from the bottom edge. Mysterious but gentle and inviting, not scary. "+STYLE.paint },
    { file:"icon-app.png", label:"앱 아이콘 (홈 화면 추가용) ★ 망고 기본 그림을 첨부할 것", size:"512×512",
      note:"홈 화면에서 48px 로 보인다. 망고의 정체성 6요소 중 48px 에서 살아남는 것은 회색 무늬·흰 줄·연두 눈 셋뿐이므로 그 셋만 크게 남기고 나머지는 단순화한다. 몸·조끼·돋보기는 넣지 않는다 — 넣으면 얼굴이 작아져 아무것도 안 보인다. 모서리가 잘리는 기기가 있으니 얼굴을 한가운데 두고 사방에 여백을 남긴다.",
      p:"App icon. Use the attached character as the exact reference for the face. Draw ONLY the cat's HEAD, large and centered, filling most of the square, on a flat mustard #d6a83c background with no border. Keep these three things bold and unmistakable: the dark grey FUR MARKING on top of the head shifted to the RIGHT so the LEFT ear stays white, the single white stripe running from forehead down to the nose, and the yellow-green eyes #b9c96a. The grey is fur, not a hat — no hat, no cap, no brim, nothing sticking up. Simplify everything else: no body, no vest, no magnifying glass, no whiskers, no background objects. Leave clear empty margin on all four sides so nothing is lost when the corners are rounded off. Very simple bold shapes that stay readable at 48 pixels. hand-drawn cel style, thick dark-brown outline #4a3428, flat matte fill, one hard shadow tone, no text, no label, no watermark" }
  ]
},

/* ───────────────────────── 5. 단서 아이콘 ───────────────────────── */
{
  title: "5. 단서 아이콘 16종 — 수첩·추리 칸에 28px로 들어간다",
  note: "작게 보이므로 물건 하나만, 굵은 선으로. 제미나이에 한 번에 여러 개를 시키면 스타일이 흔들리니 「같은 스타일로 다음 물건」을 이어서 요청한다. 증언 카드(말풍선 5종)는 말풍선 안의 그림만 바뀐다.",
  items: [
    { file:"clue-stand.png", label:"배식대의 젖은 자국",
      p:"A short section of a stainless steel serving counter seen at a slight angle, with one glistening wet ring-shaped patch on top where something round used to sit. "+STYLE.icon },
    { file:"clue-crumbs.png", label:"부스러기 자국",
      p:"A short curved trail of small crumbs on a floor, about seven crumbs getting smaller toward one end. The crumbs are the warm muddy ORANGE-BROWN colour of acorn jelly, exactly as in the background painting — never white, never pale, never grey. "+STYLE.icon },
    { file:"clue-door.png", label:"뒷문 밀대",
      p:"A heavy door seen from the inside with a horizontal push-bar across it and a small arrow showing it opens outward, no handle on the far side. "+STYLE.icon },
    { file:"clue-strap.png", label:"뒷문의 크림색 끈",
      p:"A close view of the vertical OUTER EDGE of a heavy door, drawn as a narrow upright slab of door seen from the side, with one thin CREAM-COLOURED fabric string caught over that edge and its loose end hanging straight down. Draw ONLY the string and the door edge. Do NOT draw an apron, do NOT draw a bow, do NOT tie the string around anything, and do NOT draw a handle — this door has no outer handle. "+STYLE.icon },
    { file:"clue-window.png", label:"창문 걸쇠",
      p:"A close view of a window frame corner with a small metal latch hook fastened shut on the inside. "+STYLE.icon },
    { file:"clue-print.png", label:"창턱의 붉은 발자국",
      p:"One very small five-toed animal footprint pressed in reddish-brown earth on a wooden ledge, the toes pointing toward the viewer. "+STYLE.icon },
    { file:"clue-tub.png", label:"화단의 빈 묵 통",
      p:"An empty round food tub lying tipped on its side, showing TWO handles one on each side, a little soil on the rim. "+STYLE.icon },
    { file:"clue-hook.png", label:"앞치마 걸이",
      p:"Exactly TWO wall-mounted coat hooks side by side, and BOTH hooks are completely EMPTY — nothing hanging on either of them, just the two bare hooks on the wall. "+STYLE.icon },
    { file:"clue-sink.png", label:"설거지실",
      p:"A deep stainless dish sink with a stack of clean plates beside it and a faucet above, small soap bubbles. "+STYLE.icon },
    { file:"clue-stain.png", label:"콩순이 앞치마의 얼룩",
      p:"A folded pale pink apron with one irregular brownish-grey stain on the front. "+STYLE.icon },
    { file:"clue-finger.png", label:"냉장고의 지문",
      p:"A refrigerator door handle with two glowing fingerprint smudges on it, shown with faint concentric ridge lines. "+STYLE.icon },
    { file:"clue-say-lock.png", label:"증언 · 앞문을 잠갔다",
      p:"A rounded speech bubble outline containing a small closed padlock on a door. "+STYLE.icon },
    { file:"clue-say-helpers.png", label:"증언 · 도우미 둘은 설거지실",
      p:"A rounded speech bubble outline containing two tiny identical raccoon silhouettes standing side by side beside a sink. "+STYLE.icon },
    { file:"clue-say-tub.png", label:"증언 · 통은 둘이 든다",
      p:"A rounded speech bubble outline containing a round tub with two hands, one gripping each handle on opposite sides. "+STYLE.icon },
    { file:"clue-say-doto.png", label:"증언 · 회색 꼬리",
      p:"A rounded speech bubble outline containing a single bushy GREY ringed tail disappearing around a corner. "+STYLE.icon },
    { file:"clue-say-wiped.png", label:"증언 · 창턱은 어제 닦았다",
      p:"A rounded speech bubble outline containing a cloth wiping a window ledge with a small shine mark. "+STYLE.icon }
  ]
},

/* ───────────────────── 6. 사건 2 「찢어진 축제 포스터」 ───────────────────── */
{
  title: "6. 사건 2 — 도서관 앞 게시판 (배경 1 + 단서 아이콘 10)",
  note: "사건 2는 「사건 아닌 사건」이다 — 아무도 찢지 않았고 바람이 찢었다. 그림이 그 결론과 어긋나면 게임이 거짓말을 한다. 특히 ① 젖은 흙에 발자국이 없어야 하고 ② 낙엽과 조각이 같은 한쪽으로만 몰려야 하고 ③ 압정 구멍은 위에만 둘이어야 하고 ④ 옆 게시판 포스터는 「광장」 자리만 네모나게 오려져 있어야 한다. 새 인물은 없다.",
  items: [
    { file:"scene-02-board.webp", label:"현장 — 도서관 앞 게시판", size:"1440×720 → make-bg.py 로 2:1 · WebP 200KB 이하",
      note:"조사 지점 9곳이 이 그림 위에 얹힌다. 좌표는 그림을 받은 뒤 art/spots.html 로 다시 찍는다(결정 17).",
      p:"A village library entrance seen from the front in the early morning after a night of rain. On the left a stone library wall with a window and a wooden book-return box. In the middle a large wooden notice board on two posts: one festival poster on it is TORN — only the upper part is still attached, and there are exactly TWO drawing-pin holes at its TOP corners and NO pins at the bottom. Scattered on the ground to the RIGHT of the board lie several torn paper scraps, and fallen leaves are heaped ON THE SAME RIGHT SIDE ONLY, as if one steady wind pushed everything one way. Directly in front of the board is a patch of bare wet earth that is completely SMOOTH — absolutely no footprints of any kind anywhere on it. On the right a second smaller notice board holds two intact posters, each with one clean rectangular hole neatly cut out of it with a blade. A bare tree leans slightly to the right, a red postbox and a bicycle rack stand at the edges. EVERY poster and every sign in this picture is BLANK — plain coloured paper with simple shapes and coloured bands only. Do NOT write or paint any letters, words, numbers or lettering of any kind anywhere in the picture, in any language. "+STYLE.paint },

    { file:"c2-icons-A.png", label:"사건 2 아이콘 5장 — 한 장에 나란히", size:"자르기: art/cut-icons.py <파일> c2-pieces,c2-pins,c2-leaves,c2-scatter,c2-mud",
      p:"Draw FIVE separate small object icons in ONE image, side by side in a single row, evenly spaced, in this order:\n\n(1) ONE single rectangular paper poster lying flat, broken into five pieces that have been pushed back together, the join lines fanning out WIDE toward the bottom like an open fan — clearly not one straight hand-torn line. The poster is BLANK apart from a coloured band across the top and a few plain ruled lines. It is one poster, not a fan of tickets.\n\n(2) A corner of a wooden notice board with exactly TWO small drawing pins at the TOP corners and two empty pin holes below them.\n\n(3) A small heap of fallen autumn leaves all blown to ONE side, leaning the same direction.\n\n(4) Several small torn paper scraps lying in a line, all drifted to ONE side.\n\n(5) A patch of smooth wet brown earth with a few raindrop dimples and NO footprints at all.\n\nDraw each icon SMALL, filling only the middle of its own fifth of the picture, so there is a wide band of empty cream background between them: no icon may touch, overlap or reach into a neighbouring one, and the gap between two icons must be at least as wide as one icon. Put all five in ONE straight horizontal row, never two rows. Do NOT write any letters, words or numbers anywhere, in any language. "+STYLE.icon },

    { file:"c2-icons-B.png", label:"사건 2 아이콘 5장 — 한 장에 나란히 (증언 3장은 말풍선)", size:"자르기: art/cut-icons.py <파일> c2-tape,c2-cut,c2-say-wind,c2-say-pin,c2-say-noon",
      p:"Draw FIVE separate small object icons in ONE image, side by side in a single row, evenly spaced, in this order:\n\n(1) A small empty cloth pocket turned slightly inside out, with no pins left in it.\n\n(2) A festival poster with ONE clean rectangular hole cut out of its middle with a blade — the cut edges perfectly straight, quite unlike a tear.\n\n(3) A simple speech bubble with a bent tree branch and three curved wind lines inside it.\n\n(4) A simple speech bubble with exactly two drawing pins inside it.\n\n(5) A simple speech bubble with a small sun and an undamaged poster inside it.\n\nDraw each icon SMALL, filling only the middle of its own fifth of the picture, so there is a wide band of empty cream background between them: no icon may touch, overlap or reach into a neighbouring one, and the gap between two icons must be at least as wide as one icon. No letters anywhere. "+STYLE.icon }
  ]
}
,

/* ───────────────── 7. 사건 4 「어긋난 말뚝 세 개」 ───────────────── */
{
  title: "7. 사건 4 — 반장 곰 · 토끼 삼총사 · 아이콘 10",
  note: "배경은 새로 뽑지 않는다 — 사건 3의 광장을 그대로 쓰고 말뚝·밧줄·석회는 덧그림(SVG)으로 얹어 두었다. 그림이 한 장도 없어도 사건 4는 끝까지 돌아가므로, 마음에 드는 것만 골라 넣어도 된다. ★ 순서는 인물 → 아이콘. 곰은 「시트 한 장(3칸)」으로, 토끼 삼총사는 「낱장 3장」으로 받는다 — 삼총사는 한 칸에 셋이 들어가서 자동으로 칸을 찾는 도구가 머리를 잘못 세기 때문이다.",
  items: [

    { file:"bear-STEP1.png", label:"반장 곰 · 1단계 — 기본 한 장 (★ 승인된 인물 그림 한 장을 「화풍 참고용」으로 첨부)",
      note:"곰은 새 동물 종이다. 글로만 주문하면 화풍이 무너진다(도토에서 겪음 — 외곽선이 사라지고 채도가 두 배가 됐다). 그래서 img/kongi-def.png 처럼 이미 승인된 그림을 붙이되, 「베낄 것은 화풍뿐」을 못박는다. 곰은 사건 6에서 또 나오므로 여기서 확실히 잡아 둔다. ★ 실루엣은 「큰 사각 + 안전모」 — 지금까지 쓴 어떤 인물과도 겹치지 않는다.",
      p:"The attached picture is a STYLE REFERENCE ONLY. Copy from it: the thick uniform dark-brown outline weight, the flat matte fill with exactly one hard-edged shadow tone, the eye style, the head-to-body proportion, the low-saturation muted palette, the framing and the plain background. Do NOT copy the animal species, the face, the clothing or any props from it.\n\nDraw a completely different animal: an anthropomorphic BROWN BEAR as a kind, dependable village work foreman. One single front-facing bust portrait from the chest up, centered, one figure only. Sturdy square-shouldered body — the widest silhouette of any character so far. Warm honey-brown fur, small round ears, a broad gentle muzzle, calm steady eyes looking straight at the viewer with a slight friendly smile. He wears a mustard-yellow hard hat and a teal work vest; a carpenter's pencil is tucked behind one ear and a coil of rope hangs over one shoulder. He is NOT a detective: no bow tie, no bag, no magnifying glass.\n\nPut absolutely NO letters, words, numbers or lettering of any kind anywhere in the picture, in any language — the hard hat must be plain with NO logo, the vest must be plain with NO text, and nothing may be written on the rope or the pencil. Draw him SMALL so that he fills only the MIDDLE of the picture: both shoulders and the tops of both arms completely visible, with a wide band of empty flat cream background on the LEFT, on the RIGHT and BELOW him. Nothing may touch or be cut off by any edge of the picture. Make every surface flat matte with a single hard-edged shadow tone — no gloss, no gradient, no soft shading anywhere. "+STYLE.cel },

    { file:"bear-SHEET.png", label:"반장 곰 · 2단계 — 표정 3칸 (★ 승인된 곰 1단계 그림을 첨부)", size:"자르기: python3 art/slice-sheet.py <파일> bear def,sp,fl",
      note:"첨부는 반드시 곰 자신의 1단계 그림이어야 한다. 다른 인물 그림을 붙이면 그 옷과 소품이 옮겨 붙는다(콩이가 탐정 조끼를 입고 나온 적이 있다). 세 번째 칸 「난처함」이 이 인물의 본성이다 — 자기 잘못이 아닌데 자책하는 얼굴. 곰은 말뚝을 옮기지 않았는데도 미안해하는 사람이라, 이 표정이 사건 4의 마지막 장면을 지탱한다.",
      p:"Using the attached character as the exact reference, draw the SAME brown bear foreman THREE times in one image, side by side in a single row, in this order:\n\n(1) calm and dependable, looking straight ahead — his default face;\n(2) surprised — eyes wide and round, eyebrows high, mouth a small open O, both paws raised slightly, the hard hat tilted a little back;\n(3) embarrassed and apologetic — one paw scratching the back of his head, eyes looking down and away, eyebrows slanted up in the middle, a small awkward smile, one bead of sweat on the temple; he looks like someone blaming himself for a mistake he did not make.\n\nKeep his face, body, fur colour, hard hat, vest, pencil and rope exactly as in the attached image in all three panels. The head must be the SAME SIZE and at the SAME HEIGHT in all three (identical eye line) and the body in the SAME pose — ONLY the face and the one raised paw change. Leave a clear empty gap between the panels: the figures must NOT touch or overlap each other. Plain flat cream #fbf7ee background, no dividing lines, no panel borders, no frames, no text, no labels anywhere. "+STYLE.cel },

    { file:"rabbits-def.png", label:"토끼 삼총사 · 기본 — 셋을 한 장에 (★ 승인된 인물 그림을 「화풍 참고용」으로 첨부)",
      note:"★ 토끼도 새 동물 종이라, 곰과 마찬가지로 img/kongi-def.png 같은 승인된 그림을 「화풍 참고용」으로 첨부한다(글로만 주문하면 화풍이 무너진다). 심문 카드가 하나이므로 그림도 하나다 — 셋이 늘 함께 대답한다. ★ 막내의 「한쪽 접힌 귀 + 노란 머리끈」은 반드시 들어가야 한다. 현장에서 주운 노란 머리끈이 셋을 가리키는 단서인데, 그림에 머리끈이 없으면 아이가 연결을 못 한다. 이 한 장이 마음에 들 때까지 고친 뒤, 아래 두 장은 이 그림을 첨부해서 뽑는다.",
      p:"The attached picture is a STYLE REFERENCE ONLY. Copy from it: the thick uniform dark-brown outline weight, the flat matte fill with exactly one hard-edged shadow tone, the eye style, the head-to-body proportion, the low-saturation muted palette, the framing and the plain background. Do NOT copy the animal species, the face, the clothing or any props from it.\n\nDraw completely different animals: three young rabbit siblings standing close together as one group, front-facing bust portrait from the chest up, all three fully visible side by side, one single image.\n\nLEFT — the tallest: cream-coloured fur, both ears straight up, a teal scarf.\nMIDDLE — medium height: light grey fur, both ears straight up, a brick-red scarf.\nRIGHT — the smallest: cream-coloured fur, ONE EAR FOLDED DOWN over the side of her head, wearing a bright YELLOW hair band, holding a slightly deflated soccer ball.\n\nAll three look straight at the viewer with innocent round eyes. They are children, not detectives: no vests, no bags, no magnifying glasses. Put NO letters, words, numbers or logos anywhere — the ball must be plain with NO lettering and NO logo on it. Draw them SMALL so that the group fills only the MIDDLE of the picture, with a wide band of empty flat cream background on the LEFT, on the RIGHT and BELOW them. No ear, shoulder or paw may touch or be cut off by any edge of the picture. Every surface flat matte with a single hard-edged shadow tone — no gloss, no gradient. "+STYLE.cel },

    { file:"rabbits-sp.png", label:"토끼 삼총사 · 놀람 (★ 승인된 기본 그림을 첨부)",
      p:"Using the attached image as the exact reference, draw the SAME three rabbit siblings again, same left-to-right order, same fur colours, same scarves, the same folded ear and the same yellow hair band on the smallest — one single group bust portrait, same size and same eye line as the reference.\n\nOnly the expressions change: all three are startled — eyes wide and round, ears shooting straight up (even the smallest one's folded ear springs up), mouths small open O, and the soccer ball slipping out of the smallest one's paws.\n\nDo not redesign or simplify the characters. Plain flat cream #fbf7ee background, no text anywhere. "+STYLE.cel },

    { file:"rabbits-fl.png", label:"토끼 삼총사 · 딴청 (★ 승인된 기본 그림을 첨부)",
      note:"반박당한 순간에 뜨는 얼굴이다. 셋이 서로 다른 데를 보는 것이 핵심 — 「말을 맞추지 못한 아이들」로 읽혀야 한다.",
      p:"Using the attached image as the exact reference, draw the SAME three rabbit siblings again, same left-to-right order, same fur colours, same scarves, the same folded ear and the same yellow hair band on the smallest — one single group bust portrait, same size and same eye line as the reference.\n\nOnly the expressions change: they are playing innocent and each one looks a DIFFERENT way — the tallest whistles at the sky, the middle one stares far off to the left, and the smallest looks down at the ground while hiding the ball behind her back. Nobody meets the viewer's eyes.\n\nDo not redesign or simplify the characters. Plain flat cream #fbf7ee background, no text anywhere. "+STYLE.cel },

    { file:"c4-icons-A.png", label:"사건 4 아이콘 5장 — 한 장에 나란히", size:"자르기: python3 art/cut-icons.py <파일> c4-stakes,c4-one,c4-two,c4-chalk,c4-prints",
      p:"Draw FIVE separate small object icons in ONE image, side by side in a single row, evenly spaced, in this order:\n\n(1) A row of six short wooden survey stakes standing in a line, joined by one loose sagging rope.\n\n(2) ONE wooden stake leaning over at an angle, its base loose in crumbly turned-up soil.\n\n(3) ONE wooden stake leaning the OTHER way, with a round pressed ball-mark on the stone beside its base.\n\n(4) A white chalk circle drawn on grey paving stones, smudged and scuffed across one side by footprints.\n\n(5) A small cluster of rabbit footprints in bare soil between paving stones — long narrow hind feet, clearly not shoes and clearly not paws with claws.\n\nDraw each icon SMALL, filling only the middle of its own fifth of the picture, so there is a wide band of empty cream background between them: no icon may touch, overlap or reach into a neighbouring one, and the gap between two icons must be at least as wide as one icon. Put all five in ONE straight horizontal row, never two rows. Do NOT write any letters, words or numbers anywhere, in any language. "+STYLE.icon },

    { file:"c4-icons-B.png", label:"사건 4 아이콘 5장 — 한 장에 나란히", size:"자르기: python3 art/cut-icons.py <파일> c4-ball,c4-four,c4-span,c4-ribbon,c4-sign",
      note:"★ 세 번째 「한 뼘」이 이 시트에서 가장 중요하다 — 연결판의 네 장째로 쓰이고, 28px 로 줄여 놓아도 「금과 말뚝이 한 뼘 떨어져 있다」가 읽혀야 한다. 안 읽히면 그 칸만 다시 뽑는다.",
      p:"Draw FIVE separate small object icons in ONE image, side by side in a single row, evenly spaced, in this order:\n\n(1) A slightly deflated soccer ball lying in short grass, plain with NO lettering and NO logo on it.\n\n(2) ONE wooden stake standing perfectly straight and deep, the soil packed down firmly and smoothly around its base.\n\n(3) A faint white chalk circle on paving stones that has been brushed almost away, and a wooden stake standing beside it — with a CLEAR VISIBLE GAP about one hand-span wide between the circle and the stake, and a small double-headed arrow across that gap to show the distance.\n\n(4) One small thin yellow hair band lying on the ground, short and slightly twisted.\n\n(5) A small wooden site notice board on a post, the board completely BLANK — no text, no letters, no writing and no symbols of any kind on it.\n\nDraw each icon SMALL, filling only the middle of its own fifth of the picture, so there is a wide band of empty cream background between them: no icon may touch, overlap or reach into a neighbouring one, and the gap between two icons must be at least as wide as one icon. Put all five in ONE straight horizontal row, never two rows. Do NOT write any letters, words or numbers anywhere, in any language. "+STYLE.icon }
  ]
}
,

/* ───────────────── 8. 자잘한 것 — 밝은 전신 망고 · 부엉이 표정 ───────────────── */
{
  title: "8. 자잘한 것 — 밝은 전신 망고 · 부엉이 할아버지 표정",
  note: "사건에 매인 그림은 아니지만 게임 곳곳에서 눈에 띄는 두 장이다. ★ 둘 다 **그 인물 자신의 승인된 그림을 첨부**해서 뽑는다. 받은 뒤에는 반드시 **빨강·파랑 바둑판 위에 얹어** 몸이 비치거나 눈이 뚫리지 않았는지 본다 — 어두운 단색 위에서는 멀쩡해 보인다(토끼에서 겪음).",
  items: [

    { file:"mango-full.png", label:"밝은 전신 망고 (★ mango-def.png 를 첨부)", size:"1024×1536 (세로로 긴 그림)",
      note:"지금 쓰는 전신 망고는 **회화풍이라 혼자만 어둡고 결이 다르다.** 재현·에필로그에서 이야기를 들려줄 때 이 그림이 뜨는데, 다른 인물은 전부 납작한 셀 화풍이라 혼자 튄다. 그래서 표지에서는 일부러 빼 두고 mango-joy 를 쓰고 있다. 셀 화풍으로 다시 뽑으면 표지와 이야기 장면을 모두 이 한 장으로 통일할 수 있다. ★ 머리 위 회색은 **털 무늬**다 — 모자로 그려지면 다시 뽑는다.",
      p:"Using the attached image as the exact character reference, draw the SAME detective cat — same fur colours and the exact same markings, same eyes, same teal vest, same brick-red bow tie, same leather satchel, same thick dark-brown outline weight, same flat matte colours.\n\nDraw him FULL BODY, standing upright on two short legs in a three-quarter view, both feet visible, one paw holding a brass magnifying glass at chest height, the satchel hanging at his hip, tail curving up behind him, a calm confident posture with a slight smile.\n\nThe dark grey patch on top of his head is a FUR MARKING, not clothing: flat against the head with soft irregular fur edges, NO hat, NO cap, no brim, no seam, nothing sticking up on top.\n\nDraw him SMALL so he fills only the MIDDLE of the picture, with a wide band of empty flat cream background on the LEFT, on the RIGHT and BELOW his feet. Nothing may touch or be cut off by any edge. Plain flat cream #fbf7ee background, no gradient, no gloss, no shadow on the ground, no text anywhere. "+STYLE.cel },

    { file:"owl-SHEET.png", label:"부엉이 할아버지 · 표정 3칸 (★ owl-def.png 를 첨부)", size:"자르기: python3 art/slice-sheet.py <파일> owl def,sp,fl",
      note:"사건 3의 종지기. 지금은 기본 표정 한 장뿐이라 반박에 성공해도 얼굴이 그대로다. 셋째 칸 「멋쩍음」이 이 인물의 본성이다 — 나쁜 사람이 아니라 **마흔 해 같은 일을 해 온 노인이 한 가지를 빠뜨렸을 뿐**이고, 그걸 들켰을 때 허허 웃는 얼굴이다. 무섭거나 죄스러운 얼굴이 되면 사건의 결이 무너진다.",
      p:"Using the attached character as the exact reference, draw the SAME owl grandfather THREE times in one image, side by side in a single row, in this order:\n\n(1) his calm default face, sleepy half-lidded eyes, looking straight ahead;\n(2) surprised — both eyes wide open and round, eyebrow feathers raised high, beak slightly open, the round glasses on his hat sliding down a little, one wing lifted;\n(3) sheepish and amused at himself — eyes crinkled into happy arcs, a warm \u0022heh heh\u0022 smile, one wing scratching the side of his head, head tilted, shoulders slightly raised. He is a kind old man who has just realised he skipped one small step in forty years of work — embarrassed but not guilty, not frightened, not sad.\n\nKeep his face, body, the teal knitted beanie, the round glasses on the hat, the mustard knitted scarf, the brass key and his feather colours exactly as in the attached image in all three panels. The head must be the SAME SIZE and at the SAME HEIGHT in all three (identical eye line) and the body in the SAME pose — ONLY the face and the one lifted wing change.\n\nLeave a clear empty gap between the panels: the figures must NOT touch or overlap each other. Plain flat cream #fbf7ee background, no dividing lines, no panel borders, no frames, no text and no labels anywhere. "+STYLE.cel }
  ]
}
,

/* ───────────────── 9. 사건 5 「도서관의 비 오는 날」 ───────────────── */
{
  title: "9. 사건 5 — 도서관 배경 · 오리 · 아이콘 9",
  note: "이번엔 **배경이 새로 필요하다** — 도서관 안은 처음 나오는 곳이다(모리가 일하는 곳. 아이는 「오리 사건의 배경」으로만 읽지만, 2막에서 이 방이 다시 나온다). 배경이 없어도 사건은 SVG 덧그림만으로 끝까지 돌아가니, 배경은 마지막에 뽑아도 된다. 순서는 오리(새 동물 종 → 참고 그림 첨부) → 아이콘 두 시트 → 배경. 받은 인물 그림은 **빨강·파랑 바둑판 위에 얹어** 몸이 비치지 않는지 본다.",
  items: [

    { file:"duck-STEP1.png", label:"오리 · 1단계 — 기본 한 장 (★ kongi-def.png 를 「화풍 참고용」으로 첨부)",
      note:"강가에 사는 어린 오리. 이 사건의 겉 범인인데 **태평함**이 본성이다 — 책을 우산 삼아 가져가 놓고도 「비 오는데 뭐라도 써야죠」. 미안해하지 않는 참새, 딴청 부리는 토끼, 자책하는 곰과 달라야 한다. ★ 실루엣은 「둥근 머리 + 넓적한 부리」. 흰 깃털이 단서(c5-feather)이므로 **흰색** 오리여야 한다 — 노란 오리로 나오면 다시 뽑는다.",
      p:"The attached picture is a STYLE REFERENCE ONLY. Copy from it: the thick uniform dark-brown outline weight, the flat matte fill with exactly one hard-edged shadow tone, the eye style, the head-to-body proportion, the low-saturation muted palette, the framing and the plain background. Do NOT copy the animal species, the face, the clothing or any props from it.\n\nDraw a completely different animal: a young WHITE duck child, front-facing bust portrait from the chest up, one figure only, centered. Round head, plump white body with soft cream shading, a wide flat ORANGE bill, small round black eyes with a single tiny dot highlight, one little tuft of feathers on top of the head. Wears a simple brick-red neckerchief and nothing else — no vest, no bag, no glasses, no hat. Relaxed, carefree, slightly sleepy expression with a small easy smile, as if nothing in the world is a problem.\n\nThe feathers must be WHITE (not yellow) — a white feather is a clue in the story. Put NO letters, words, numbers or logos anywhere.\n\nFRAMING, the most important part: this is NOT a close-up of his face. His head must be only about ONE THIRD of the picture's height. His head, neck, shoulders, chest and BOTH little folded wings at his sides must all be fully inside the picture, none of them touching or crossing any edge. Leave a wide band of empty flat cream background all around him — at least one fifth of the picture width empty on the LEFT and on the RIGHT, and empty cream below his chest. A picture where his cheeks reach the left and right edges, or where his body is cut off at the bottom, is wrong and must be redrawn smaller.\n\nEvery surface flat matte with a single hard-edged shadow tone — no gloss, no gradient. "+STYLE.cel },

    { file:"duck-SHEET.png", label:"오리 · 2단계 — 표정 3칸 (★ 승인된 오리 1단계 그림을 첨부)", size:"자르기: python3 art/slice-sheet.py <파일> duck def,sp,fl",
      note:"셋째 칸 「태평함」이 본성이다. 반박당해도 놀라지 않고 「아, 그 책이요?」 하는 얼굴. 놀람과 태평함이 섞이지 않도록 각 칸에 「이건 아니다」를 넣어 두었다.",
      p:"Using the attached character as the exact reference, draw the SAME white duck child THREE times in one image, side by side in a single row, in this order:\n\n(1) his relaxed default face, small easy smile, looking straight ahead;\n(2) surprised — eyes wide and round, bill slightly open, the tuft of feathers standing straight up, both wings raised a little; he is NOT smiling in this panel;\n(3) carefree and unbothered — eyes half-closed in a lazy contented way, a wide easy grin, head tilted, one wing scratching his belly; he looks like someone who has just been told he did something wrong and does not mind at all. He is NOT startled in this panel, his eyes are NOT wide.\n\nKeep his face, body, white feathers, orange bill and brick-red neckerchief exactly as in the attached image in all three panels. The head must be the SAME SIZE and at the SAME HEIGHT in all three (identical eye line) and the body in the SAME pose — ONLY the face and one wing change. In every panel his head, neck, shoulders, chest and BOTH wings must be fully visible and nothing may be cut off at the top, bottom, left or right — this is a bust, never a close-up of the face. Draw the three figures SMALL, each filling only the middle of its own third of the picture, and leave a clear empty gap between the panels at least as wide as one of their heads: the figures must NOT touch or overlap each other. Plain flat cream #fbf7ee background, no dividing lines, no panel borders, no frames, no text and no labels anywhere. "+STYLE.cel },

    { file:"c5-icons-A.png", label:"사건 5 아이콘 5장 — 한 장에 나란히", size:"자르기: python3 art/cut-icons.py <파일> c5-box,c5-soil,c5-floor,c5-table,c5-feather",
      note:"★ 「바닥에 남은 자국」류는 **네모 조각으로 그리지 말라**고 못박아야 한다(사건 4에서 겪음 — 회색 네모가 나와 28px에서 색덩어리가 됐다). 물건처럼, 불규칙한 윤곽 한 덩어리로.",
      p:"Draw FIVE separate small object icons in ONE image, side by side in a single row, evenly spaced, each one a distinct OBJECT floating on a plain flat cream #fbf7ee background. Do NOT draw a square tile, a rectangular patch, a photo crop or a framed panel — each icon must be an irregular outlined shape with empty cream all around it.\n\n(1) A small wooden book-return box with a slanted lid propped half open by a big picture book sticking out of it; the lid is wet and shiny, the inside dry.\n\n(2) A small heap of DRY reddish-brown crumbly soil with a few grass roots and one small green leaf fragment in it — dusty and dry, clearly not mud.\n\n(3) THREE webbed duck footprints in a line going away, wet and bluish, getting smaller — the nearest one biggest, the farthest one smallest, with one tiny water drop beside the biggest. Draw ONLY the footprint shapes floating on empty cream — no floor, no plank, no board, no tile, no square patch under them.\n\n(4) A small wooden reading table with an open picture book on it and one wet wooden chair beside it, a few water drops on the seat.\n\n(5) One small WHITE feather with a few water drops on it, curved, lying alone.\n\nDraw each icon SMALL, filling only the middle of its own fifth of the picture, with a wide band of empty cream between them. Strong dark-brown outlines #4a3428 on every shape, flat matte fill, one hard shadow tone, high contrast — each icon must still be readable when shrunk to 28 pixels. Put all five in ONE straight horizontal row, never two rows. No text, no letters, no numbers anywhere. "+STYLE.icon },

    { file:"c5-icons-B.png", label:"사건 5 아이콘 4장 — 한 장에 나란히", size:"자르기: python3 art/cut-icons.py <파일> c5-paper,c5-web,c5-boots,c5-book",
      note:"★ 「c5-book」은 반드시 **크고 두꺼운 그림책이 젖어 물결친** 모양 — 심문에서 오리가 「집에 있어요」 할 때 사진으로 뜬다.",
      p:"Draw FOUR separate small object icons in ONE image, side by side in a single row, evenly spaced, each one a distinct OBJECT floating on a plain flat cream #fbf7ee background. Do NOT draw a square tile, a rectangular patch, a photo crop or a framed panel — each icon must be an irregular outlined shape with empty cream all around it.\n\n(1) A folded newspaper lying on a doorstep, soaked through and limp, with water drops on it; the newspaper is BLANK — grey bands and lines only, no letters.\n\n(2) THREE webbed duck footprints pressed into dark wet mud, in a line heading away, with a small clump of grass beside them. Draw only the prints and the grass as one irregular shape on empty cream — no square patch of ground, no plank, no tile, no frame.\n\n(3) TWO large boot prints in wet brown mud, chunky treaded soles, side by side. Draw only the two print shapes on empty cream — no square patch of ground, no plank, no tile, no frame.\n\n(4) A big thick picture book with a sky-blue cover showing only a simple white cloud shape, its pages WAVY and warped from getting wet, a few water drops sliding off the cover. NO title, NO letters, NO writing on the cover.\n\nDraw each icon SMALL, filling only the middle of its own quarter of the picture, with a wide band of empty cream between them. Strong dark-brown outlines #4a3428 on every shape, flat matte fill, one hard shadow tone, high contrast — each icon must still be readable when shrunk to 28 pixels. Put all four in ONE straight horizontal row, never two rows. No text, no letters, no numbers anywhere. "+STYLE.icon },

    { file:"scene-05-library.webp", label:"현장 — 도서관 안 (배경)", size:"1440×720 → make-bg.py 로 2:1 · WebP 200KB 이하",
      note:"조사 지점 11곳이 이 그림 위에 얹힌다 — 지금은 SVG 덧그림이 방을 대신 그리고 있으니, 배경을 받으면 **덧그림의 벽·바닥·창·서가·탁자·문을 빼고** 자국·신문·깃털·흙 같은 단서만 남긴다. 좌표는 그림을 받은 뒤 art/spots.html 로 다시 찍는다. ★ 문은 **왼쪽 벽**, 반납함은 **문 바로 안쪽**, 열람 탁자는 **앞쪽 가운데**, 서가는 **오른쪽** — 덧그림과 자리가 같아야 좌표를 조금만 옮기면 된다.",
      p:"The inside of a small cosy village library on a rainy afternoon, seen from the reading area looking toward the far wall, eye level. LEFT: a wooden front door standing open, and through it grey rain falling on a muddy doorstep. Just inside the door, against the wall, a small wooden book-return box with a slanted lid. CENTER, at the back: a tall window with rain streaking down the glass and a grey sky outside. RIGHT: a tall wooden bookshelf full of books with plain coloured spines, and in front of it a small librarian's desk with a stamp and a ledger. FRONT CENTER: a low wooden reading table with two wooden chairs. The floor is worn wooden planks, EMPTY and clean — no footprints, no puddles, no objects on the floor (those are added later). Warm lamplight inside against the cool grey rain outside. EVERY book spine, sign and paper in this picture is BLANK — plain colour bands only. Do NOT write or paint any letters, words, numbers or lettering of any kind anywhere in the picture, in any language. "+STYLE.paint }
  ]
}
];
